redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  user: root
  pass:

wechat: # 微信小程序相关配置 (切记不能泄漏）
  appid:
  appsecret:

dev: true

server:
  port: "8088"
  allow_origins:
    - "http://localhost:3000"

db:
  user_name: "root"
  password: "pwd"
  address: "127.0.0.1:3306"
  db_name: "img_db"

jwt:
  secret: "secretKey"
  issuer: "issuer"
  expires: 48