redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  user: root
  pass:

server:
  port: "8088"

db:
  user_name: "root"
  password: "pwd"
  address: "127.0.0.1:3306"
  db_name: "img_db"

jwt:
  secret: "secretKey"
  issuer: "issuer"
  expires: 48